[package]
name = "echoip"
version = "0.1.0"
authors = ["Michael Laccetti <michael@laccetti.com>"]
edition = "2018"

[[bin]]
name = "echoip"
path = "src/main.rs"

[dependencies]
actix-web = "3.3.2"
askama = "0.10.5"
env_logger = "0.8.3"
lazy_static = "1.4.0"
log = "0.4.14"
maxminddb = "0.17.2"

[build-dependencies]
askama = "0.10.5"
