unstable_features = true

reorder_imports = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_modules = true
newline_style = "Unix"
tab_spaces = 2
trailing_comma = "Never"
use_field_init_shorthand = true
