name: CI Build

on:
  push:
    branches-ignore:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Compile
      run: cargo build --verbose
    - name: Tests
      run: cargo test --verbose
